# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J9tmCCk8bMBydsHymXYDBR-v42Pe1O_-
"""

! pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

! streamlit run streamlit.py & npx localtunnel --port 8501