# -*- coding: utf-8 -*-
"""Transcription.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQWEdbZuKRKpT0AJJ-o_KJsg1j1WfQYn
"""

!pip install pytube openai-whisper

# Initialize a YouTube object
import os
from pytube import YouTube
import whisper
import warnings

warnings.filterwarnings("ignore", message="FP16 is not supported on CPU; using FP32 instead")
# YouTube video URL
youtube_url = "https://www.youtube.com/watch?v=uweW8QlXMZI&t=532s"

# Output file name
output_file = "output.web3"

# Create a temporary directory to store the video and audio files
temp_dir = "temp"
os.makedirs(temp_dir, exist_ok=True)
yt = YouTube(youtube_url)
title=yt.title
name=title[:-3]+".mp4"
file_location = "/content/"+temp_dir+"/"+name
stream = yt.streams.filter(only_audio=True, file_extension="mp4").first()
stream.download(output_path=temp_dir)
model = whisper.load_model("base")
result = model.transcribe(file_location)
print(result["text"])



